sudo: required

language: php

php:
  - 7.1

services:
  - docker

git:
  depth: false

dist: trusty
addons:
  chrome: stable
 ⋮
before_install:
  - composer install
  - cd web/app/themes/hmcts-km
  - npm install
  - npm install -g bower
  - npm install -g gulp
  - rm -Rf node_modules bower_components
  - cd ../../../..
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - docker-compose -f docker-compose-travis.yml up -d
  - gem install dory
  - dory up
  - dory status
  - docker-compose -f docker-compose-travis.yml exec wordpress features/seed-database.sh -d

script:
  - vendor/bin/behat

notifications:
  email: false
